export const DELATNOSTI: Record<string, string> = {
  "1011": "Prerada i konzervisanje mesa",
  "1012": "Prerada i konzervisanje živinskog mesa",
  "1013": "Proizvodnja mesnih prerađevina",
  "1020": "Prerada i konzervisanje ribe, ljuskara i mekušaca",
  "1031": "Prerada i konzervisanje krompira",
  "1032": "Proizvodnja sokova od voća i povrća",
  "1039": "Ostala prerada i konzervisanje voća i povrća",
  "1041": "Proizvodnja ulja i masti",
  "1042": "Proizvodnja margarina i sličnih jestivih masti",
  "1051": "Prerada mleka i proizvodnja sireva",
  "1052": "Proizvodnja sladoleda",
  "1061": "Proizvodnja mlinskih proizvoda",
  "1062": "Proizvodnja skroba i skrobnih proizvoda",
  "1071": "Proizvodnja hleba, svežeg peciva i kolača",
  "1072": "Proizvodnja dvopeka, keksa, trajnog peciva i kolača",
  "1073": "Proizvodnja makarona, rezanaca i sličnih proizvoda",
  "1081": "Proizvodnja šećera",
  "1082": "Proizvodnja čokolade i konditorskih proizvoda",
  "1083": "Prerada čaja i kafe",
  "1084": "Proizvodnja začina i drugih dodataka hrani",
  "1085": "Proizvodnja gotovih jela",
  "1086": "Proizvodnja hranljivih preparata i dijetetske hrane",
  "1089": "Proizvodnja ostalih prehrambenih proizvoda",
  "1091": "Proizvodnja gotove hrane za domaće životinje",
  "1092": "Proizvodnja gotove hrane za kućne ljubimce",
  "1101": "Destilacija, prečišćavanje i mešanje pića",
  "1102": "Proizvodnja vina od grožđa",
  "1103": "Proizvodnja pića i ostalih voćnih vina",
  "1104": "Proizvodnja nedestilovanih fermentisanih pića",
  "1105": "Proizvodnja piva",
  "1106": "Proizvodnja slada",
  "1107": "Proizvodnja osvežavajućih pića i flaširane vode",
  "1200": "Proizvodnja duvanskih proizvoda",
  "1310": "Priprema i predenje tekstilnih vlakana",
  "1320": "Proizvodnja tkanina",
  "1330": "Dovršavanje tekstila",
  "1391": "Proizvodnja pletenih i kukičanih materijala",
  "1392": "Proizvodnja gotovih tekstilnih proizvoda, osim odeće",
  "1393": "Proizvodnja tepiha i prekrivača za pod",
  "1394": "Proizvodnja užadi, kanapa, pletenica i mreža",
  "1395": "Proizvodnja netkanog tekstila i predmeta, osim odeće",
  "1396": "Proizvodnja tehničkog i industrijskog tekstila",
  "1399": "Proizvodnja ostalih tekstilnih predmeta",
  "1411": "Proizvodnja kožne odeće",
  "1412": "Proizvodnja radne odeće",
  "1413": "Proizvodnja ostale odeće",
  "1414": "Proizvodnja rublja",
  "1419": "Proizvodnja ostalih odevnih predmeta i pribora",
  "1420": "Proizvodnja proizvoda od krzna",
  "1431": "Proizvodnja pletenih i kukičanih čarapa",
  "1439": "Proizvodnja ostale pletene i kukičane odeće",
  "1511": "Štavljenje i dorada kože, dorada i bojenje krzna",
  "1512": "Proizvodnja putnih i ručnih torbi i kaiševa",
  "1520": "Proizvodnja obuće",
  "1610": "Rezanje i obrada drveta",
  "1621": "Proizvodnja furnira i ploča od drveta",
  "1622": "Proizvodnja parketa",
  "1623": "Proizvodnja ostale građevinske stolarije i elemenata",
  "1624": "Proizvodnja drvne ambalaže",
  "1629": "Proizvodnja proizvoda od drveta, plute, slame i pruća",
  "1711": "Proizvodnja vlakana celuloze",
  "1712": "Proizvodnja papira i kartona",
  "1721": "Proizvodnja talasastog papira, kartona i ambalaže",
  "1722": "Proizvodnja predmeta od papira za ličnu upotrebu",
  "1723": "Proizvodnja kancelarijskih predmeta od papira",
  "1724": "Proizvodnja tapeta",
  "1729": "Proizvodnja ostalih proizvoda od papira i kartona",
  "1811": "Štampanje novina",
  "1812": "Ostalo štampanje",
  "1813": "Usluge pripreme za štampu",
  "1814": "Knjigovezačke i srodne usluge",
  "1820": "Umnožavanje snimljenih zapisa",
  "1910": "Proizvodnja produkata koksovanja",
  "1920": "Proizvodnja derivata nafte",
  "2011": "Proizvodnja industrijskih gasova",
  "2012": "Proizvodnja sredstava za pripremanje boja i pigmenata",
  "2013": "Proizvodnja ostalih osnovnih neorganskih hemikalija",
  "2014": "Proizvodnja ostalih osnovnih organskih hemikalija",
  "2015": "Proizvodnja veštačkih đubriva i azotnih jedinjenja",
  "2016": "Proizvodnja plastičnih masa u primarnim oblicima",
  "2017": "Proizvodnja sintetičkog kaučuka",
  "2020": "Proizvodnja pesticida i hemikalija za poljoprivredu",
  "2030": "Proizvodnja boja, lakova i sličnih premaza",
  "2041": "Proizvodnja deterdženata, sapuna i sredstava za čišćenje",
  "2042": "Proizvodnja parfema i toaletnih preparata",
  "2051": "Proizvodnja eksploziva",
  "2052": "Proizvodnja sredstava za lepljenje",
  "2053": "Proizvodnja eteričnih ulja",
  "2059": "Proizvodnja ostalih hemijskih proizvoda",
  "2060": "Proizvodnja veštačkih vlakana",
  "2110": "Proizvodnja osnovnih farmaceutskih proizvoda",
  "2120": "Proizvodnja farmaceutskih preparata",
  "2211": "Proizvodnja guma za vozila, protektiranje guma",
  "2219": "Proizvodnja ostalih proizvoda od gume",
  "2221": "Proizvodnja ploča, listova, cevi i profila",
  "2222": "Proizvodnja ambalaže od plastike",
  "2223": "Proizvodnja predmeta od plastike za građevinarstvo",
  "2229": "Proizvodnja ostalih proizvoda od plastike",
  "2311": "Proizvodnja ravnog stakla",
  "2312": "Oblikovanje i obrada ravnog stakla",
  "2313": "Proizvodnja šupljeg stakla",
  "2314": "Proizvodnja staklenih vlakana",
  "2319": "Proizvodnja i obrada ostalog stakla",
  "2320": "Proizvodnja vatrostalnih proizvoda",
  "2331": "Proizvodnja keramičkih pločica i ploča",
  "2332": "Proizvodnja opeke, crepa i građevinskih proizvoda",
  "2341": "Proizvodnja keramičkih predmeta za domaćinstvo",
  "2342": "Proizvodnja sanitarnih keramičkih proizvoda",
  "2343": "Proizvodnja izolatora i izolac. pribora od keramike",
  "2344": "Proizvodnja ostalih tehničkih proizvoda od keramike",
  "2349": "Proizvodnja ostalih keramičkih proizvoda",
  "2351": "Proizvodnja cementa",
  "2352": "Proizvodnja kreča i gipsa",
  "2361": "Proizvodnja proizvoda od betona za građevinarstvo",
  "2362": "Proizvodnja proizvoda od gipsa za građevinarstvo",
  "2363": "Proizvodnja svežeg betona",
  "2364": "Proizvodnja maltera",
  "2365": "Proizvodnja proizvoda od cementa s vlaknima",
  "2369": "Proizvodnja ostalih proizvoda od betona i gipsa",
  "2370": "Sečenje, oblikovanje i obrada kamena",
  "2391": "Proizvodnja brusnih proizvoda",
  "2399": "Proizvodnja proizvoda od nemetalnih minerala",
  "2410": "Proizvodnja sirovog gvožđa, čelika i ferolegura",
  "2420": "Proizvodnja čeličnih cevi, profila i fitinga",
  "2431": "Hladno valjanje šipki",
  "2432": "Hladno valjanje pljosnatih proizvoda",
  "2433": "Hladno oblikovanje profila",
  "2434": "Hladno vučenje žice",
  "2441": "Proizvodnja plemenitih metala",
  "2442": "Proizvodnja aluminijuma",
  "2443": "Proizvodnja olova, cinka i kalaja",
  "2444": "Proizvodnja bakra",
  "2445": "Proizvodnja ostalih obojenih metala",
  "2446": "Proizvodnja nuklearnog goriva",
  "2451": "Livenje gvožđa",
  "2452": "Livenje čelika",
  "2453": "Livenje lakih metala",
  "2454": "Livenje ostalih obojenih metala",
  "2511": "Proizvodnja metalnih konstrukcija i delova",
  "2512": "Proizvodnja metalnih vrata i prozora",
  "2521": "Proizvodnja kotlova i radijatora za grejanje",
  "2529": "Proizvodnja ostalih metalnih cisterni i kontejnera",
  "2530": "Proizvodnja parnih kotlova, osim za centr. grejanje",
  "2540": "Proizvodnja oružja i municije",
  "2550": "Kovanje, presovanje, štancovanje i valjanje metala",
  "2561": "Obrada i prevlačenje metala",
  "2562": "Mašinska obrada metala",
  "2571": "Proizvodnja sečiva",
  "2572": "Proizvodnja brava i okova",
  "2573": "Proizvodnja alata",
  "2591": "Proizvodnja čeličnih buradi i slične ambalaže",
  "2592": "Proizvodnja ambalaže od lakih metala",
  "2593": "Proizvodnja žičanih proizvoda, lanaca i opruga",
  "2594": "Proizvodnja veznih elemenata i vijčanih proizvoda",
  "2599": "Proizvodnja ostalih metalnih proizvoda",
  "2611": "Proizvodnja elektronskih elemenata",
  "2612": "Proizvodnja štampanih elektronskih ploča",
  "2620": "Proizvodnja računara i periferne opreme",
  "2630": "Proizvodnja komunikacione opreme",
  "2640": "Proizvodnja elektronskih uređaja za široku potrošnju",
  "2651": "Proizvodnja mernih instrumenata i aparata",
  "2652": "Proizvodnja satova",
  "2660": "Proizvodnja elektromedicinske opreme",
  "2670": "Proizvodnja optičkih instrumenata i fotogr. opreme",
  "2680": "Proizvodnja magnetnih i optičkih nosilaca zapisa",
  "2711": "Proizvodnja elektromot. generatora i transformatora",
  "2712": "Proizvodnja opreme za distribuciju elektr. energije",
  "2720": "Proizvodnja baterija i akumulatora",
  "2731": "Proizvodnja kablova od optičkih vlakana",
  "2732": "Proizvodnja ostalih elektronskih i elektr. kablova",
  "2733": "Proizvodnja opreme za povezivanje žica i kablova",
  "2740": "Proizvodnja opreme za osvetljenje",
  "2751": "Proizvodnja električnih aparata za domaćinstvo",
  "2752": "Proizvodnja neelektričnih aparata za domaćinstvo",
  "2790": "Proizvodnja ostale električne opreme",
  "2811": "Proizvodnja motora i turbina, osim za motorna vozila",
  "2812": "Proizvodnja hidrauličnih pogonskih uređaja",
  "2813": "Proizvodnja ostalih pumpi i kompresora",
  "2814": "Proizvodnja ostalih slavina i ventila",
  "2815": "Proizvodnja ležajeva, zupčanika i zupčastih elemenata",
  "2821": "Proizvodnja industrijskih peći i gorionika",
  "2822": "Proizvodnja opreme za podizanje i prenošenje",
  "2823": "Proizvodnja kancelarijskih mašina i opreme",
  "2824": "Proizvodnja ručnih pogonskih aparata sa mehanizmima",
  "2825": "Proizvodnja rashladne i ventilacione opreme",
  "2829": "Proizvodnja ostalih mašina i aparata opšte namene",
  "2830": "Proizvodnja mašina za poljoprivredu i šumarstvo",
  "2841": "Proizvodnja mašina za obradu metala",
  "2849": "Proizvodnja ostalih alatnih mašina",
  "2891": "Proizvodnja mašina za metalurgiju",
  "2892": "Proizvodnja mašina za rudnike i građevinarstvo",
  "2893": "Proizvodnja mašina za industr. hrane, pića i duvana",
  "2894": "Proizvodnja mašina za industr. tekstila, odeće i kože",
  "2895": "Proizvodnja mašina za industriju papira i kartona",
  "2896": "Proizvodnja mašina za izradu plastike i gume",
  "2899": "Proizvodnja mašina za ostale specijalne namene",
  "2910": "Proizvodnja motornih vozila",
  "2920": "Proizvodnja karoserija za motorna vozila i prikolice",
  "2931": "Proizvodnja električne opreme za motorna vozila",
  "2932": "Proizvodnja ostalih delova za motorna vozila",
  "3011": "Izgradnja brodova i plovnih objekata",
  "3012": "Izrada čamaca za sport i razonodu",
  "3020": "Proizvodnja lokomotiva i šinskih vozila",
  "3030": "Proizvodnja vazdušnih i svemirskih letelica",
  "3040": "Proizvodnja borbenih vojnih vozila",
  "3091": "Proizvodnja motocikala",
  "3092": "Proizvodnja bicikala i invalidskih kolica",
  "3099": "Proizvodnja ostale transportne opreme",
  "3101": "Proizvodnja nameštaja za poslovne prostore",
  "3102": "Proizvodnja kuhinjskog nameštaja",
  "3103": "Proizvodnja madraca",
  "3109": "Proizvodnja ostalog nameštaja",
  "3211": "Kovanje novca",
  "3212": "Proizvodnja nakita i srodnih predmeta",
  "3213": "Proizvodnja imitacije nakita i srodnih proizvoda",
  "3220": "Proizvodnja muzičkih instrumenata",
  "3230": "Proizvodnja sportske opreme",
  "3240": "Proizvodnja igara i igračaka",
  "3250": "Proizvodnja medicinskih i stomatoloških materijala",
  "3291": "Proizvodnja metli i četki",
  "3299": "Proizvodnja ostalih predmeta",
  "3311": "Popravka metalnih proizvoda",
  "3312": "Popravka mašina",
  "3313": "Popravka elektronske i optičke opreme",
  "3314": "Popravka električne opreme",
  "3315": "Popravka i održavanje brodova i čamaca",
  "3316": "Popravka i održavanje letelica",
  "3317": "Popravka i održavanje druge transportne opreme",
  "3319": "Popravka ostale opreme",
  "3320": "Montaža industrijskih mašina i opreme",
  "3511": "Proizvodnja električne energije",
  "3512": "Prenos električne energije",
  "3513": "Distribucija električne energije",
  "3514": "Trgovina električnom energijom",
  "3521": "Proizvodnja gasa",
  "3522": "Distribucija gasovitih goriva gasovodom",
  "3523": "Trgovina gasovitim gorivima preko gasovodne mreže",
  "3530": "Snabdevanje parom i klimatizacija",
  "3600": "Skupljanje, prečišćavanje i distribucija vode",
  "3700": "Uklanjanje otpadnih voda",
  "3811": "Skupljanje otpada koji nije opasan",
  "3812": "Skupljanje opasnog otpada",
  "3821": "Tretman i odlaganje otpada koji nije opasan",
  "3822": "Tretman i odlaganje opasnog otpada",
  "3831": "Demontaža olupina",
  "3832": "Ponovna upotreba razvrstanih materijala",
  "3900": "Sanacija, rekultivacija i upravljanje otpadom",
  "4110": "Razrada građevinskih projekata",
  "4120": "Izgradnja stambenih i nestambenih zgrada",
  "4211": "Izgradnja puteva i autoputeva",
  "4212": "Izgradnja železničkih pruga i podzemnih železnica",
  "4213": "Izgradnja mostova i tunela",
  "4221": "Izgradnja cevovoda",
  "4222": "Izgradnja električnih i telekomunikacionih vodova",
  "4291": "Izgradnja hidrotehničkih objekata",
  "4299": "Izgradnja ostalih nepomenutih građevina",
  "4311": "Rušenje objekata",
  "4312": "Pripremanje gradilišta",
  "4313": "Ispitivanje terena bušenjem i sondiranjem",
  "4321": "Postavljanje električnih instalacija",
  "4322": "Postavljanje vodovodnih i klimatizacionih sistema",
  "4329": "Ostali instalacioni radovi u građevinarstvu",
  "4331": "Malterisanje",
  "4332": "Ugradnja stolarije",
  "4333": "Postavljanje podnih i zidnih obloga",
  "4334": "Bojenje i zastakljivanje",
  "4339": "Ostali završni radovi",
  "4391": "Krovni radovi",
  "4399": "Ostali nepomenuti specifični građevinski radovi",
  "4511": "Trgovina automobilima i lakim motornim vozilima",
  "4519": "Trgovina ostalim motornim vozilima",
  "4520": "Održavanje i popravka motornih vozila",
  "4531": "Trgovina na veliko delovima i opremom za vozila",
  "4532": "Trgovina na malo delovima i opremom za vozila",
  "4540": "Trgovina motociklima, delovima i popravka motocik.",
  "4611": "Posredovanje u prodaji poljoprivrednih sirovina",
  "4612": "Posredovanje u prodaji goriva, ruda i metala",
  "4613": "Posredovanje u prodaji građevinskog materijala",
  "4614": "Posredovanje u prodaji mašina i industrijske opreme",
  "4615": "Posredovanje u prodaji nameštaja i metalne robe",
  "4616": "Posredovanje u prodaji tekstila, odeće, krzna i obuće",
  "4617": "Posredovanje u prodaji hrane, pića i duvana",
  "4618": "Specijalizovano posredovanje u prodaji proizvoda",
  "4619": "Posredovanje u prodaji raznovrsnih proizvoda",
  "4621": "Trgovina na veliko žitom, sirovim duvanom i semenjem",
  "4622": "Trgovina na veliko cvećem i sadnicama",
  "4623": "Trgovina na veliko životinjama",
  "4624": "Trgovina na veliko sirovom i dovršenom kožom",
  "4631": "Trgovina na veliko voćem i povrćem",
  "4632": "Trgovina na veliko mesom i proizvodima od mesa",
  "4633": "Trgovina na veliko mlečnim proizvodima i mastima",
  "4634": "Trgovina na veliko pićima",
  "4635": "Trgovina na veliko duvanskim proizvodima",
  "4636": "Trgovina na veliko šećerom, čokoladom i slatkišima",
  "4637": "Trgovina na veliko kafom, čajevima, kakaom i začinima",
  "4638": "Trgovina na veliko ostalom hranom, uključujući ribu",
  "4639": "Nespecijalizovana trgovina na veliko hranom i pićima",
  "4641": "Trgovina na veliko tekstilom",
  "4642": "Trgovina na veliko odećom i obućom",
  "4643": "Trgovina na veliko elektr. aparatima za domaćinstvo",
  "4644": "Trgovina na veliko porculanom i staklenom robom",
  "4645": "Trgovina na veliko parfimerijskim proizvodima",
  "4646": "Trgovina na veliko farmaceutskim proizvodima",
  "4647": "Trgovina na veliko nameštajem i tepisima",
  "4648": "Trgovina na veliko satovima i nakitom",
  "4649": "Trgovina na veliko ostalim proizvodima",
  "4651": "Trgovina na veliko računarima i softverima",
  "4652": "Trgovina na veliko elektronskim delovima i opremom",
  "4661": "Trgovina na veliko poljoprivrednim mašinama",
  "4662": "Trgovina na veliko alatnim mašinama",
  "4663": "Trgovina na veliko rudarskim i građ. mašinama",
  "4664": "Trgovina na veliko mašinama za tekstilnu industriju",
  "4665": "Trgovina na veliko kancelarijskim nameštajem",
  "4666": "Trgovina na veliko ostalim kancelarijskim mašinama",
  "4669": "Trgovina na veliko ostalim mašinama i opremom",
  "4671": "Trgovina na veliko čvrstim i tečnim gorivima",
  "4672": "Trgovina na veliko metalima i metalnim rudama",
  "4673": "Trgovina na veliko drvetom i građ. materijalom",
  "4674": "Trgovina na veliko metalnom robom",
  "4675": "Trgovina na veliko hemijskim proizvodima",
  "4676": "Trgovina na veliko ostalim poluproizvodima",
  "4677": "Trgovina na veliko otpacima i ostacima",
  "4690": "Nespecijalizovana trgovina na veliko",
  "4711": "Trgovina na malo u nespec. prodavn. pretežno hranom",
  "4719": "Ostala trgovina na malo u nespecijaliz. prodavnicama",
  "4721": "Trgovina na malo voćem i povrćem",
  "4722": "Trgovina na malo mesom i proizvodima od mesa",
  "4723": "Trgovina na malo ribom, ljuskarima i mekušcima",
  "4724": "Trgovina na malo hlebom, kolačima i slatkišima",
  "4725": "Trgovina na malo pićima",
  "4726": "Trgovina na malo proizvodima od duvana",
  "4729": "Ostala trgovina na malo hranom u spec. prodavnicama",
  "4730": "Trgovina na malo motornim gorivima",
  "4741": "Trgovina na malo računarima i softverom",
  "4742": "Trgovina na malo telekomunikacionom opremom",
  "4743": "Trgovina na malo audio i video opremom",
  "4751": "Trgovina na malo tekstilom u spec. prodavnicama",
  "4752": "Trgovina na malo metalnom robom, bojama i staklom",
  "4753": "Trgovina na malo tepisima, zidnim i podnim oblogama",
  "4754": "Trgovina na malo elektr. aparatima za domaćinstvo",
  "4759": "Trgovina na malo nameštajem i ostalim predmetima",
  "4761": "Trgovina na malo knjigama u spec. prodavnicama",
  "4762": "Trgovina na malo novinama i kancelar. materijalom",
  "4763": "Trgovina na malo muzičkim i video zapisima",
  "4764": "Trgovina na malo sportskom opremom",
  "4765": "Trgovina na malo igrama i igračkama",
  "4771": "Trgovina na malo odećom u spec. prodavnicama",
  "4772": "Trgovina na malo obućom i predmetima od kože",
  "4773": "Trgovina na malo farmaceutskim proizv. u apotekama",
  "4774": "Trgovina na malo medicinskim i ortoped. pomagalima",
  "4775": "Trgovina na malo kozmetičkim i toaletnim proizv.",
  "4776": "Trgovina na malo cvećem, sadnicama i semenjem",
  "4777": "Trgovina na malo satovima i nakitom",
  "4778": "Ostala trgovina na malo novim proizvodima",
  "4779": "Trgovina na malo polovnom robom u prodavnicama",
  "4781": "Trgovina na malo hranom, pićima na pijacama",
  "4782": "Trgovina na malo tekstilom i obućom na pijacama",
  "4789": "Trgovina na malo ostalom robom na tezgama i pijacama",
  "4791": "Trgovina na malo posredstvom pošte ili interneta",
  "4799": "Ostala trgovina na malo izvan prodavnica i pijaca",
  "4910": "Železnički prevoz putnika, daljinski i regionalni",
  "4920": "Železnički prevoz tereta",
  "4931": "Gradski i prigradski kopneni prevoz putnika",
  "4932": "Taksi prevoz",
  "4939": "Ostali prevoz putnika u kopnenom saobraćaju",
  "4941": "Drumski prevoz tereta",
  "4942": "Usluge preseljenja",
  "4950": "Cevovodni transport",
  "5010": "Pomorski i priobalni prevoz putnika",
  "5020": "Pomorski i priobalni prevoz tereta",
  "5030": "Prevoz putnika unutrašnjim plovnim putevima",
  "5040": "Prevoz tereta unutrašnjim plovnim putevima",
  "5110": "Vazdušni prevoz putnika",
  "5121": "Vazdušni prevoz tereta",
  "5122": "Vasionski saobraćaj",
  "5210": "Skladištenje",
  "5221": "Uslužne delatnosti u kopnenom saobraćaju",
  "5222": "Uslužne delatnosti u vodenom saobraćaju",
  "5223": "Uslužne delatnosti u vazdušnom saobraćaju",
  "5224": "Manipulacija teretom",
  "5229": "Ostale prateće delatnosti u saobraćaju",
  "5310": "Poštanske aktivnosti javnog servisa",
  "5320": "Poštanske aktivnosti komercijalnog servisa",
  "5510": "Hoteli i sličan smeštaj",
  "5520": "Odmarališta i slični objekti za kraći boravak",
  "5530": "Delatnost kampova i auto-kampova",
  "5590": "Ostali smeštaj",
  "5610": "Delatnosti restorana i pokretnih ugostitelj. objekta",
  "5621": "Ketering",
  "5629": "Ostale usluge pripremanja i posluživanja hrane",
  "5630": "Usluge pripremanja i posluživanja pića",
  "5811": "Izdavanje knjiga",
  "5812": "Izdavanje imenika i adresara",
  "5813": "Izdavanje novina",
  "5814": "Izdavanje časopisa i periodičnih izdanja",
  "5819": "Ostala izdavačka delatnost",
  "5821": "Izdavanje računarskih igara",
  "5829": "Izdavanje ostalih softvera",
  "5911": "Proizvodnja kinematografskih dela i TV programa",
  "5912": "Delatnosti nakon snimanja kinematograf. dela i TV",
  "5913": "Distribucija kinematografskih dela i TV programa",
  "5914": "Delatnost prikazivanja kinematografskih dela",
  "5920": "Snimanje i izdavanje zvučnih zapisa i muzike",
  "6010": "Emitovanje radio-programa",
  "6020": "Proizvodnja i emitovanje televizijskog programa",
  "6110": "Kablovske telekomunikacije",
  "6120": "Bežične telekomunikacije",
  "6130": "Satelitske telekomunikacije",
  "6190": "Ostale telekomunikacione delatnosti",
  "6201": "Računarsko programiranje",
  "6202": "Konsultantske delat. u informacionim tehnologijama",
  "6203": "Upravljanje računarskom opremom",
  "6209": "Ostale usluge informacione tehnologije",
  "6311": "Obrada podataka, hosting i sl.",
  "6312": "Veb portali",
  "6391": "Delatnosti novinskih agencija",
  "6399": "Informacione uslužne delatnosti",
  "6411": "Centralna banka",
  "6419": "Ostalo monetarno posredovanje",
  "6420": "Delatnost holding kompanija",
  "6430": "Poverenički fondovi i investicioni fondovi",
  "6491": "Finansijski lizing",
  "6492": "Ostale usluge kreditiranja",
  "6499": "Ostale finans. usluge, osim osiguranja i penz. fondova",
  "6511": "Životno osiguranje",
  "6512": "Neživotno osiguranje",
  "6520": "Reosiguranje",
  "6530": "Penzijski fondovi",
  "6611": "Finansijske i robne berze",
  "6612": "Brokerski poslovi s hartijama i berzanskom robom",
  "6619": "Ostale pomoćne delatnosti u finans. uslugama",
  "6621": "Obrada odštetnih zahteva i procenjivanje rizika i šteta",
  "6622": "Delatnost zastupnika i posrednika u osiguranju",
  "6629": "Ostale pomoćne delat. u osiguranju i penz. fondovima",
  "6630": "Upravljanje fondovima",
  "6810": "Kupovina i prodaja vlastitih nekretnina",
  "6820": "Iznajmljivanje nekretnina i upravljanje njima",
  "6831": "Delatnost agencija za nekretnine",
  "6832": "Upravljanje nekretninama za naknadu",
  "6910": "Pravni poslovi",
  "6920": "Računovodstveni, knjigov. i revizorski poslovi",
  "7010": "Upravljanje ekonomskim subjektom",
  "7021": "Delatnost komunikacija i odnosa s javnošću",
  "7022": "Konsultantske aktivnosti u vezi s poslovanjem",
  "7111": "Arhitektonska delatnost",
  "7112": "Inženjerske delatnosti i tehničko savetovanje",
  "7120": "Tehničko ispitivanje i analize",
  "7211": "Istraživanje i razvoj u biotehnologiji",
  "7219": "Istraživanje i razvoj u ostalim prirodnim naukama",
  "7220": "Istraživanje i razvoj u društvenim i human. naukama",
  "7311": "Delatnost reklamnih agencija",
  "7312": "Medijsko predstavljanje",
  "7320": "Istraživanje tržišta i ispitivanje javnog mnjenja",
  "7410": "Specijalizovane dizajnerske delatnosti",
  "7420": "Fotografske usluge",
  "7430": "Prevođenje i usluge tumača",
  "7490": "Ostale stručne, naučne i tehničke delatnosti",
  "7500": "Veterinarska delatnost",
  "7711": "Iznajmljivanje i lizing automobila i motornih vozila",
  "7712": "Iznajmljivanje i lizing kamiona",
  "7721": "Iznajmljivanje i lizing opreme za rekreaciju i sport",
  "7722": "Iznajmljivanje video-kaseta i kompakt-diskova",
  "7729": "Iznajmljivanje i lizing ostalih predmeta",
  "7731": "Iznajmljivanje i lizing poljoprivrednih mašina",
  "7732": "Iznajmljivanje i lizing mašina za građevinarstvo",
  "7733": "Iznajmljivanje i lizing kancelarijskih mašina",
  "7734": "Iznajmljivanje i lizing opreme za vodeni transport",
  "7735": "Iznajmljivanje i lizing opreme za vazdušni transport",
  "7739": "Iznajmljivanje i lizing ostalih mašina i opreme",
  "7740": "Lizing intelektualne svojine i sličnih proizvoda",
  "7810": "Delatnost agencija za zapošljavanje",
  "7820": "Delatnost agencija za privremeno zapošljavanje",
  "7830": "Ostalo ustupanje ljudskih resursa",
  "7911": "Delatnost putničkih agencija",
  "7912": "Delatnost tur-operatora",
  "7990": "Ostale usluge rezervacije",
  "8010": "Delatnost privatnog obezbeđenja",
  "8020": "Usluge sistema obezbeđenja",
  "8030": "Istražne delatnosti",
  "8110": "Usluge održavanja objekata",
  "8121": "Usluge redovnog čišćenja zgrada",
  "8122": "Usluge ostalog čišćenja zgrada i opreme",
  "8129": "Usluge ostalog čišćenja",
  "8130": "Usluge uređenja i održavanja okoline",
  "8211": "Kombinovane kancelarijsko-administrativne usluge",
  "8219": "Fotokopiranje i druga kancelarijska podrška",
  "8220": "Delatnost pozivnih centara",
  "8230": "Organizovanje sastanaka i sajmova",
  "8291": "Delatnost agencija za naplatu potraživanja",
  "8292": "Usluge pakovanja",
  "8299": "Ostale uslužne aktivnosti podrške poslovanju",
  "8411": "Delatnost državnih organa",
  "8412": "Uređivanje subjekata koji pružaju društvene usluge",
  "8413": "Uređenje poslovanja u oblasti ekonomije",
  "8421": "Spoljni poslovi",
  "8422": "Poslovi odbrane",
  "8423": "Sudske i pravosudne delatnosti",
  "8424": "Obezbeđivanje javnog reda i bezbednosti",
  "8425": "Delatnost vatrogasnih jedinica",
  "8430": "Obavezno socijalno osiguranje",
  "8510": "Predškolsko obrazovanje",
  "8520": "Osnovno obrazovanje",
  "8531": "Srednje opšte obrazovanje",
  "8532": "Srednje stručno obrazovanje",
  "8541": "Obrazovanje posle srednjeg koje nije visoko",
  "8542": "Visoko obrazovanje",
  "8551": "Sportsko i rekreativno obrazovanje",
  "8552": "Umetničko obrazovanje",
  "8553": "Delatnost škola za vozače",
  "8559": "Ostalo obrazovanje",
  "8560": "Pomoćne obrazovne delatnosti",
  "8610": "Delatnost bolnica",
  "8621": "Opšta medicinska praksa",
  "8622": "Specijalistička medicinska praksa",
  "8623": "Stomatološka praksa",
  "8690": "Ostala zdravstvena zaštita",
  "8710": "Delatnost smeštajnih ustanova s medicinskom negom",
  "8720": "Socijalno staranje u smeštajnim ustanovama",
  "8730": "Rad ustanova za lica s posebnim potrebama",
  "8790": "Ostali oblici socijalne zaštite sa smeštajem",
  "8810": "Socijalna zaštita bez smeštaja za stara lica",
  "8891": "Delatnost dnevne brige o deci",
  "8899": "Ostala nepomenuta socijalna zaštita bez smeštaja",
  "9001": "Izvođačka umetnost",
  "9002": "Druge umetničke delatnosti u okviru izvođačke umetnosti",
  "9003": "Umetničko stvaralaštvo",
  "9004": "Rad umetničkih ustanova",
  "9101": "Delatnost biblioteka i arhiva",
  "9102": "Delatnost muzeja, galerija i zbirki",
  "9103": "Zaštita i održavanje nepokretnih kulturnih dobara",
  "9104": "Delatnost botaničkih i zooloških vrtova",
  "9200": "Kockanje i klađenje",
  "9311": "Delatnost sportskih objekata",
  "9312": "Delatnost sportskih klubova",
  "9313": "Delatnost fitnes klubova",
  "9319": "Ostale sportske delatnosti",
  "9321": "Delatnost zabavnih i tematskih parkova",
  "9329": "Ostale zabavne i rekreativne delatnosti",
  "9411": "Delatnost poslovnih udruženja i poslodavaca",
  "9412": "Delatnost strukovnih udruženja",
  "9420": "Delatnost sindikata",
  "9491": "Delatnost verskih organizacija",
  "9492": "Delatnost političkih organizacija",
  "9499": "Delatnost ostalih organizacija na bazi učlanjenja",
  "9511": "Popravka računara i periferne opreme",
  "9512": "Popravka komunikacione opreme",
  "9521": "Popravka elektronskih aparata za široku upotrebu",
  "9522": "Popravka aparata za domaćinstvo i kućne opreme",
  "9523": "Popravka obuće i predmeta od kože",
  "9524": "Održavanje i popravka nameštaja",
  "9525": "Popravka satova i nakita",
  "9529": "Popravka ostalih ličnih predmeta",
  "9601": "Pranje i hemijsko čišćenje tekstilnih proizvoda",
  "9602": "Delatnost frizerskih i kozmetičkih salona",
  "9603": "Pogrebne i srodne delatnosti",
  "9604": "Delatnost nege i održavanja tela",
  "9609": "Ostale nepomenute lične uslužne delatnosti",
  "9700": "Domaćinstava koja zapošljavaju poslugu",
  "9810": "Domaćinstava koja proizvode robu za sebe",
  "9820": "Domaćinstava koja obezbeđuju usluge za sebe",
  "9900": "Delatnost eksteritorijalnih organizacija i tela",
  "0111": "Gajenje žita (osim pirinča), leguminoza i uljarica",
  "0112": "Gajenje pirinča",
  "0113": "Gajenje povrća, korenastih i krtolastih biljaka",
  "0114": "Gajenje šećerne trske",
  "0115": "Gajenje duvana",
  "0116": "Gajenje biljaka za proizvodnju vlakana",
  "0119": "Gajenje ostalih jednogodišnjih i dvogodišnjih biljaka",
  "0121": "Gajenje grožđa",
  "0122": "Gajenje tropskog i suptropskog voća",
  "0123": "Gajenje agruma",
  "0124": "Gajenje jabučastog i koštičavog voća",
  "0125": "Gajenje ostalog žbunastog i jezgrastog voća",
  "0126": "Gajenje uljnih plodova",
  "0127": "Gajenje biljaka za pripremanje napitaka",
  "0128": "Gajenje začinskog, aromatičnog i lekovitog bilja",
  "0129": "Gajenje ostalih višegodišnjih biljaka",
  "0130": "Gajenje sadnog materijala",
  "0141": "Uzgoj muznih krava",
  "0142": "Uzgoj drugih goveda i bivola",
  "0143": "Uzgoj konja i drugih kopitara",
  "0144": "Uzgoj kamila i lama",
  "0145": "Uzgoj ovaca i koza",
  "0146": "Uzgoj svinja",
  "0147": "Uzgoj živine",
  "0149": "Uzgoj ostalih životinja",
  "0150": "Mešovita poljoprivredna proizvodnja",
  "0161": "Uslužne delatnosti u gajenju useva i zasada",
  "0162": "Pomoćne delatnosti u uzgoju životinja",
  "0163": "Aktivnosti posle žetve",
  "0164": "Dorada semena",
  "0170": "Lov, traperstvo i odgovarajuće uslužne delatnosti",
  "0210": "Gajenje šuma i ostale šumarske delatnosti",
  "0220": "Seča drveća",
  "0230": "Sakupljanje šumskih plodova",
  "0240": "Uslužne delatnosti u vezi sa šumarstvom",
  "0311": "Morski ribolov",
  "0312": "Slatkovodni ribolov",
  "0321": "Morske akvakulture",
  "0322": "Slatkovodne akvakulture",
  "0510": "Eksploatacija kamenog uglja i antracita",
  "0520": "Eksploatacija lignita i mrkog uglja",
  "0610": "Eksploatacija sirove nafte",
  "0620": "Eksploatacija prirodnog gasa",
  "0710": "Eksploatacija ruda gvožđa",
  "0721": "Eksploatacija ruda urana i torijuma",
  "0729": "Eksploatacija ruda obojenih metala",
  "0811": "Eksploatacija građevinskog i ukrasnog kamena",
  "0812": "Eksploatacija šljunka, peska, gline i kaolina",
  "0891": "Eksploatacija minerala",
  "0892": "Eksploatacija treseta",
  "0893": "Eksploatacija natrijum-hlorida",
  "0899": "Eksploatacija ostalih nemetaličnih ruda i minerala",
  "0910": "Uslužne delatnosti u vezi sa naftom i gasom",
  "0990": "Uslužne delatnosti u vezi sa ostalim rudama"
};

export function getDelatnostOpis(sifra: string): string | null {
  const normalized = sifra.replace(/./g, "").trim();
  return DELATNOSTI[normalized] || null;
}
